import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Autogenerated from the help/ folder tree (see apps/docs/CONTRIBUTING.md).
const sidebars: SidebarsConfig = {
  helpSidebar: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
