import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * The sidebar is fully autogenerated from the folder structure under `docs/`.
 *
 * This is the key maintainability lever: to add a page you drop a Markdown file
 * into the right folder and (optionally) set `sidebar_position` in its frontmatter.
 * Category labels/order come from each folder's `_category_.json`. You never edit
 * this file to add content.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
