/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { pluginRequestFromWeb } from '@aglyn/aglyn/server'
import {
  emailUnverifiedResponse,
  firebaseAdmin,
  isImpersonationSession,
} from '@aglyn/tenant-data-admin'
import { createPrivateKey, sign as nodeSign } from 'node:crypto'
import { FieldValue } from 'firebase-admin/firestore'

/**
 * Staff trust-signing for realm plugins (AGL-420). Granting writes
 * `{trust: 'realm', signature}` onto the listing's version doc, where the
 * signature is the platform Ed25519 key's signature over the version's
 * sha256 hex — the loaders (client blob-import + env-gated server import)
 * verify it against `PLUGIN_TRUST_PUBLIC_KEY` before a byte executes.
 * Super staff only: a realm grant lets marketplace code run in the app
 * realm of every workspace that installs it, the largest blast radius any
 * staff action has. Revoking removes the grant (already-loaded realms
 * pick it up on next load; use `revocations/{listingId}` for the hard
 * kill switch).
 *
 * `PLUGIN_TRUST_PRIVATE_KEY` is the base64 PKCS8 DER Ed25519 private key
 * (pair generated by `tools/scripts/generate-plugin-trust-key.mjs`) —
 * deployed ONLY to the console app, never to tenant runtimes.
 */
async function handler(request: Request): Promise<Response> {
  const { method, body, headers: rawHeaders } = await pluginRequestFromWeb(request)
  const headers = rawHeaders as Partial<Record<string, string>>
  if (method !== 'POST') {
    return Response.json({ error: 'Method not allowed' }, { status: 405 })
  }
  const authorization = headers.authorization ?? ''
  const idToken = authorization.startsWith('Bearer ')
    ? authorization.slice('Bearer '.length)
    : undefined
  if (!idToken) return Response.json({ error: 'Unauthenticated' }, { status: 401 })

  try {
    const decoded = await firebaseAdmin.app().auth().verifyIdToken(idToken)
    if (!decoded.email_verified && !isImpersonationSession(decoded)) {
      return emailUnverifiedResponse()
    }
    if (!decoded['staff']) {
      return Response.json({ error: 'Staff only' }, { status: 403 })
    }
    if (String(decoded['staffRole'] ?? 'super') !== 'super') {
      return Response.json({ error: 'Requires the super staff role' }, { status: 403 })
    }

    const listingId = String(body?.listingId ?? '')
    const version = String(body?.version ?? '')
    const action = body?.action === 'revoke' ? 'revoke' : 'grant'
    if (!listingId || !version) {
      return Response.json({ error: 'Missing listingId or version' }, { status: 400 })
    }

    const versionRef = firebaseAdmin
      .app()
      .firestore()
      .collection('communityListings')
      .doc(listingId)
      .collection('pluginVersions')
      .doc(version)
    const snapshot = await versionRef.get()
    const sha256 = snapshot.get('sha256')
    if (typeof sha256 !== 'string' || !sha256) {
      return Response.json({ error: 'Unknown plugin version' }, { status: 404 })
    }

    if (action === 'grant') {
      const privateKeyBase64 = process.env.PLUGIN_TRUST_PRIVATE_KEY
      if (!privateKeyBase64) {
        return Response.json({
          error:
            'Trust signing is not configured (missing PLUGIN_TRUST_PRIVATE_KEY)',
        }, { status: 501 })
      }
      const privateKey = createPrivateKey({
        key: Buffer.from(privateKeyBase64, 'base64'),
        format: 'der',
        type: 'pkcs8',
      })
      // Ed25519 signs the message directly (no digest algorithm).
      const signature = nodeSign(null, Buffer.from(sha256), privateKey).toString(
        'base64',
      )
      await versionRef.set(
        {
          trust: 'realm',
          signature,
          trustGrantedBy: decoded.uid,
          trustGrantedAt: FieldValue.serverTimestamp(),
        },
        { merge: true },
      )
    } else {
      await versionRef.set(
        {
          trust: FieldValue.delete(),
          signature: FieldValue.delete(),
          trustGrantedBy: FieldValue.delete(),
          trustGrantedAt: FieldValue.delete(),
        },
        { merge: true },
      )
    }

    await firebaseAdmin
      .app()
      .firestore()
      .collection('adminAudit')
      .add({
        actorUid: decoded.uid,
        action: `plugins.trust.${action}`,
        target: `communityListings/${listingId}/pluginVersions/${version}`,
        after: action === 'grant' ? { trust: 'realm' } : { trust: null },
        at: FieldValue.serverTimestamp(),
      })

    return Response.json({ ok: true, action, listingId, version }, { status: 200 })
  } catch (error) {
    console.error(error)
    return Response.json({ error: 'Trust signing failed' }, { status: 500 })
  }
}

export const dynamic = 'force-dynamic'
export { handler as POST }
